name: Publish API docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pages: write

jobs:
  publish:
    name: Publish API docs
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -ieo pipefail {0}

    steps:
      - name: Checkout Larecs
        uses: actions/checkout@v3
      - name: Install pixi CLI
        run: |
          curl -ssL https://pixi.sh/install.sh | bash

      - name: Run AoS benchmarks
        run: |
          cd benchmark/plots
          pixi run plots

      - name: Archive benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: aos-benchmark
          path: benchmark/plots/results

      - name: Copy benchmark results to docs
        run: |
          mkdir -p docs/src/guide/images
          cp benchmark/plots/results/aos_benchmark.svg docs/src/guide/images/

      - name: Build docs # Includes 'modo build', 'mojo doc', 'mojo test' and 'hugo -s docs/site'
        run: |
          pixi install --locked
          pixi run build-docs

      - name: Archive Doc-tests
        uses: actions/upload-artifact@v4
        with:
          name: doctest
          path: docs/test
      - name: Archive Markdown artifacts
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: docs/site/content
      - name: Archive HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: docs/site/public

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/site/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
